language: ruby

sudo: false

cache: bundler

rvm:
  - 1.9.3
  - jruby-19mode
  - 2.1

before_install:
  - gem update --system
  - gem update bundler

script: rake ci

notifications:
  slack:
    secure: WAn5zR+P0LYPC6feqWJOIsDEsSWNMw4qam1vl9+i4XYwRxlc7GXL10Cxfqw23okkDJLaQiCxa/Qw/oDANgCZzlg8hGS+49R6VTTjnnKB8oOJ9fIziGEDEDR+6WaQlO8cC+f39+FwIych4aLsTsODgIYj2UEqTc0rEyCUlzRBh9I=
